blank_issues_enabled: true
contact_links:
  - name: Security Vulnerability
    url: https://github.com/Dashtid/windows-linux-sysadmin-toolkit/security/policy
    about: Please report security vulnerabilities privately via the Security Policy
  - name: Question or Discussion
    url: https://github.com/Dashtid/windows-linux-sysadmin-toolkit/discussions
    about: For questions and general discussions, use GitHub Discussions
