name: Secret Detection

# Runs on every push and pull request to detect secrets before they reach main branch
on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  gitleaks:
    name: Gitleaks Secret Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for comprehensive scanning

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}  # Optional: for Gitleaks Pro
        with:
          config-path: .gitleaks.toml  # Optional: custom config

  trufflehog:
    name: TruffleHog Secret Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

  security-summary:
    name: Security Scan Summary
    runs-on: ubuntu-latest
    needs: [gitleaks, trufflehog]
    if: always()

    steps:
      - name: Check scan results
        run: |
          echo "[i] Security scan completed"
          if [ "${{ needs.gitleaks.result }}" == "failure" ] || [ "${{ needs.trufflehog.result }}" == "failure" ]; then
            echo "[-] FAIL: Secrets detected! Review the logs above."
            exit 1
          else
            echo "[+] PASS: No secrets detected"
          fi
